name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  archive:
    name: Archive Ckt
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf ieee123.ckt *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ckt
          path: ieee123.ckt
  archive-solar-ramp:
    name: Archive Solar Ramp Ckt
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: solar-ramp
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: |
          shopt -s globstar
          tar -cvf ieee123-solar_ramp.ckt **/*.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ckt-solar-ramp
          path: ieee123-solar_ramp.ckt

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions: write-all
    needs: [ archive, archive-solar-ramp ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ckt
      - uses: actions/download-artifact@v4
        with:
          name: ckt-solar-ramp

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Ckt artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ieee123.ckt
          asset_name: ieee123-${{ github.ref_name }}.ckt
          asset_content_type: application/x-tar

      - name: Upload Solar Ramp Ckt artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ieee123-solar_ramp.ckt
          asset_name: ieee123-solar_ramp-${{ github.ref_name }}.ckt
          asset_content_type: application/x-tar
